"use client";
import { useEffect, useMemo, useState } from "react";
type GmailStatus={connected:boolean;email?:string|null;sessionExpiresAt?:number}; type Job={id:string;title:string;company:string;location:string;type:string;posted_at?:string|null;apply_url?:string|null}; type TrackerItem={id:string;job_title:string;company:string;location:string|null;status:string;last_action_at:string}; type Profile={cvName:string|null;cvUploadedAt:string|null};
function remaining(x?:number){if(!x)return "";const n=Math.max(0,x-Date.now());return `${Math.floor(n/3600000)}h ${Math.floor((n%3600000)/60000)}m`;} function date(x?:string|null){return x?new Date(x).toLocaleDateString():"";} function posted(x?:string|null){if(!x)return "Recent";const d=Math.floor((Date.now()-new Date(x).getTime())/86400000);return d<=0?"Today":`${d}d ago`;}
export default function Home(){const [tab,setTab]=useState<"Jobs"|"Tracker"|"Profile">("Jobs");const [jobs,setJobs]=useState<Job[]>([]);const [tracker,setTracker]=useState<TrackerItem[]>([]);const [profile,setProfile]=useState<Profile>({cvName:null,cvUploadedAt:null});const [gmail,setGmail]=useState<GmailStatus>({connected:false});const [left,setLeft]=useState("");const [notice,setNotice]=useState("");const [loading,setLoading]=useState(false);
 async function loadJobs(){const url="/api/jobs?location=Goa";const started=performance.now();console.groupCollapsed("%c[JobApp] Jobs discovery request","font-weight:bold");console.log("URL:",url);console.log("Started:",new Date().toISOString());try{const r=await fetch(url,{cache:"no-store"});const elapsed=Math.round(performance.now()-started);console.log("HTTP:",r.status,r.statusText);console.log("Elapsed:",`${elapsed}ms`);console.log("Cache:",r.headers.get("x-vercel-cache")||"n/a");console.log("Age:",r.headers.get("age")||"n/a");const raw=await r.text();let d:any;try{d=JSON.parse(raw);}catch{console.warn("Response was not JSON:",raw);throw new Error(`Invalid JSON response (${r.status})`);}console.log("Jobs returned:",Array.isArray(d.jobs)?d.jobs.length:"unknown");console.log("Jobs:",d.jobs||[]);console.log("Freshness days:",d.freshnessDays);console.log("Source:",d.source);console.log("Discovery result:",d.discovery||null);if(d.discovery){console.log("Discovery skipped:",d.discovery?.skipped??false);console.log("Discovery sources:",d.discovery?.sources||d.discovery?.sourceResults||null);console.log("Discovery totals:",d.discovery?.totals||d.discovery?.counts||null);console.log("Discovery errors:",d.discovery?.errors||d.discovery?.error||null);}if(r.ok){setJobs(d.jobs||[]);}else{console.error("Jobs API failed:",d);}}catch(e){console.error("Jobs request exception:",e);}finally{console.log("Finished:",new Date().toISOString());console.groupEnd();}}
 async function loadTracker(){const r=await fetch("/api/tracker",{cache:"no-store"});if(r.ok){const d=await r.json();setTracker(d.items||[]);}} async function loadProfile(){const r=await fetch("/api/profile",{cache:"no-store"});if(r.ok){const d=await r.json();if(d.profile)setProfile({cvName:d.profile.cv_name??null,cvUploadedAt:d.profile.cv_uploaded_at??null});}} async function loadGmail(){const r=await fetch("/api/gmail/status",{cache:"no-store"});if(r.ok){const d=await r.json();setGmail(d);setLeft(remaining(d.sessionExpiresAt));}}
 useEffect(()=>{loadJobs();loadTracker();loadProfile();loadGmail();},[]); useEffect(()=>{const i=window.setInterval(()=>{setLeft(remaining(gmail.sessionExpiresAt));if(gmail.sessionExpiresAt&&gmail.sessionExpiresAt<=Date.now())loadGmail();},30000);return()=>window.clearInterval(i);},[gmail.sessionExpiresAt]); useEffect(()=>{if(tab==="Tracker")loadTracker();if(tab==="Profile")loadProfile();},[tab]);
 const counts=useMemo(()=>({a:tracker.filter(x=>x.status==="Applied").length,i:tracker.filter(x=>x.status==="Interview").length,f:tracker.filter(x=>x.status==="Follow-up").length}),[tracker]);
 async function upload(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;if(file.type!=="application/pdf"||file.size>10*1024*1024){setNotice("Please upload a PDF CV up to 10 MB.");return;}setLoading(true);try{const f=new FormData();f.append("cv",file);const r=await fetch("/api/profile",{method:"POST",body:f});const d=await r.json();if(!r.ok)throw new Error(d.error||"Upload failed");setProfile({cvName:d.profile?.cv_name??file.name,cvUploadedAt:d.profile?.cv_uploaded_at??new Date().toISOString()});setNotice("CV uploaded successfully.");}catch(e){setNotice(e instanceof Error?e.message:"Unable to upload CV");}finally{setLoading(false);}}
 async function disconnect(){await fetch("/api/gmail/disconnect",{method:"POST"});setGmail({connected:false});setLeft("");}
 return <main className="app-shell"><header className="topbar"><div><span className="eyebrow">JOBAPP</span><h1>Find your next role.</h1></div></header><section className={gmail.connected?"gmail-card connected":"gmail-card"}><div><div className="status-line"><span className={gmail.connected?"status-dot":"status-dot offline"}/><strong>{gmail.connected?"Gmail Connected":"Gmail Not Connected"}</strong></div><p>{gmail.connected?`${gmail.email??"Gmail account"} · Session expires in ${left||"12h"}`:"Connect Gmail to enable sending application emails."}</p></div>{gmail.connected?<button className="secondary-button" onClick={disconnect}>Disconnect</button>:<a className="primary-button" href="/api/gmail/connect">Connect Gmail</a>}</section>{notice&&<div className="notice">{notice}</div>}
 {tab==="Jobs"&&<section className="jobs-section"><div className="section-heading"><div><span className="eyebrow">GOA · LAST 15 DAYS</span><h2>Recent Goa jobs</h2></div><span className="job-count">{jobs.length} matching</span></div><div className="job-list">{jobs.map(j=><article className="job-card" key={j.id}><a className="job-card-main" href={`/jobs/${j.id}`} aria-label={`Open ${j.title} at ${j.company}`}><div className="job-card-top"><div><h3>{j.title}</h3><p>{j.company}</p></div><span className="match">{posted(j.posted_at)}</span></div></a><div className="apply-row">{j.apply_url?<a className="primary-button compact" href={j.apply_url} target="_blank" rel="noreferrer">Apply</a>:<span className="disabled-note">Company application link unavailable</span>}</div></article>)}{!jobs.length&&<div className="empty-state">No recent Goa jobs are stored yet.</div>}</div></section>}
 {tab==="Tracker"&&<section className="tracker-section"><div className="section-heading"><div><span className="eyebrow">TRACKER</span><h2>Your applications</h2></div><span className="job-count">{tracker.length} total</span></div><div className="tracker-summary"><div><strong>{counts.a}</strong><span>Applied</span></div><div><strong>{counts.i}</strong><span>Interview</span></div><div><strong>{counts.f}</strong><span>Follow-ups</span></div></div><div className="job-list">{tracker.map(x=><article className="job-card" key={x.id}><div className="job-card-top"><div><h3>{x.job_title}</h3><p>{x.company}</p></div><span className="status-pill">{x.status}</span></div><div className="job-meta"><span>{x.location||"Goa"}</span><span>·</span><span>{date(x.last_action_at)}</span></div></article>)}{!tracker.length&&<div className="empty-state">Applications you send will appear here.</div>}</div></section>}
 {tab==="Profile"&&<section className="profile-section"><span className="eyebrow">PROFILE</span><h2>Your CV</h2><p className="profile-help">Your CV is stored securely and used when generating application emails.</p><div className="cv-upload-card"><div><strong>{profile.cvName?"CV uploaded":"No CV uploaded"}</strong><p>{profile.cvName?`${profile.cvName}${profile.cvUploadedAt?` · ${date(profile.cvUploadedAt)}`:""}`:"PDF only · maximum 10 MB"}</p></div><label className="upload-button">{profile.cvName?"Upload New CV":"Upload CV"}<input type="file" accept="application/pdf,.pdf" onChange={upload} disabled={loading}/></label></div></section>}
 <nav className="bottom-nav" aria-label="Primary navigation">{(["Jobs","Tracker","Profile"] as const).map(x=><button key={x} className={tab===x?"nav-active":""} onClick={()=>setTab(x)}>{x==="Jobs"?"⌂":x==="Tracker"?"▣":"♙"}<span>{x}</span></button>)}</nav></main>}
