"use client";
import { useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
type Person={id:string;name:string;title?:string|null;email?:string|null;linkedin_url?:string|null};
type Job={id:string;title:string;company:string;location:string;type:string;description?:string|null;apply_url?:string|null;posted_at?:string|null};
type Draft={subject:string;body:string;fitScore?:number;fitReasons?:string[];cvName?:string|null};
function posted(x?:string|null){return x?new Date(x).toLocaleDateString():"Recent";}
export default function JobContacts(){
 const params=useParams<{id:string}>();const router=useRouter();const [job,setJob]=useState<Job|null>(null);const [company,setCompany]=useState<any>(null);const [people,setPeople]=useState<Person[]>([]);const [selected,setSelected]=useState<string[]>([]);const [loading,setLoading]=useState(true);const [emailLoading,setEmailLoading]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [drafts,setDrafts]=useState<Record<string,Draft>>({});const [common,setCommon]=useState<Draft|null>(null);const [modal,setModal]=useState<"jd"|"personal"|"common"|null>(null);const [active,setActive]=useState<Person|null>(null);const [busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{try{const r=await fetch(`/api/jobs/${params.id}/contacts`,{method:"POST",cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to find HR contacts");setJob(d.job);setCompany(d.company);setPeople((d.decisionMakers||[]).slice(0,10));}catch(e){setError(e instanceof Error?e.message:"Unable to load job");}finally{setLoading(false);}})()},[params.id]);
 const toggle=(id:string)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):x.length<10?[...x,id]:x);
 const getEmails=async()=>{const chosen=people.filter(p=>selected.includes(p.id)&&p.linkedin_url);if(!chosen.length)return;setEmailLoading(true);setNotice("");try{const r=await fetch(`/api/jobs/${params.id}/contact-emails`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({linkedinUrls:chosen.map(p=>p.linkedin_url)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to find email addresses");const map=new Map((d.contacts||[]).map((x:any)=>[x.linkedin_url,x.email]));setPeople(x=>x.map(p=>map.has(p.linkedin_url)?{...p,email:map.get(p.linkedin_url)}:p));setNotice(`${d.contacts?.length||0} email address${d.contacts?.length===1?"":"es"} found.`);}catch(e){setNotice(e instanceof Error?e.message:"Unable to find email addresses");}finally{setEmailLoading(false);}};
 const selectedWithEmail=people.filter(p=>selected.includes(p.id)&&p.email);
 const generatePersonal=async(p:Person)=>{if(!p.email)return;setActive(p);setModal("personal");if(drafts[p.id])return;setBusy(true);try{const r=await fetch("/api/gemini/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({job:{...job,contact_email:p.email,decision_maker_name:p.name,decision_maker_title:p.title}})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to generate email");setDrafts(x=>({...x,[p.id]:d}));}catch(e){setNotice(e instanceof Error?e.message:"Unable to generate email");setModal(null);}finally{setBusy(false);}};
 const generateCommon=async()=>{if(!selectedWithEmail.length)return;setModal("common");if(common)return;setBusy(true);try{const r=await fetch("/api/gemini/common",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({job,contacts:selectedWithEmail})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to generate common email");setCommon(d);}catch(e){setNotice(e instanceof Error?e.message:"Unable to generate common email");setModal(null);}finally{setBusy(false);}};
 const send=async(to:string[],draft:Draft)=>{if(!to.length)return;setBusy(true);try{const r=await fetch("/api/gmail/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bcc:to,subject:draft.subject,text:draft.body})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to send");if(job)await fetch("/api/tracker",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId:job.id,jobTitle:job.title,company:job.company,location:job.location,status:"Applied",subject:draft.subject,applicationBody:draft.body})});setNotice(`Email sent to ${to.length} recipient${to.length===1?"":"s"}.`);setModal(null);}catch(e){setNotice(e instanceof Error?e.message:"Unable to send email");}finally{setBusy(false);}};
 if(loading)return <main className="app-shell"><div className="empty-state">Finding HR and Talent Acquisition people at this company…</div></main>;
 if(error||!job)return <main className="app-shell"><button className="secondary-button" onClick={()=>router.back()}>← Back</button><div className="notice">{error||"Job not found"}</div></main>;
 return <main className="app-shell"><header className="topbar"><div><button className="text-link" onClick={()=>router.back()}>← Jobs</button><span className="eyebrow">SELECTED JOB</span><h1>{job.title}</h1><p>{job.company} · {job.location}</p></div></header>{notice&&<div className="notice">{notice}</div>}
 <section className="job-detail-card"><div className="job-card-top"><div><h2>{job.title}</h2><p>{job.company}</p></div><span className="match">{posted(job.posted_at)}</span></div><div className="job-meta"><span>{job.location}</span><span>·</span><span>{job.type}</span></div><div className="detail-actions"><button className="secondary-button" onClick={()=>setModal("jd")}>View JD</button>{job.apply_url&&<a className="primary-button" href={job.apply_url} target="_blank" rel="noreferrer">Apply on company page</a>}</div></section>
 <section className="contacts-section"><div className="section-heading"><div><span className="eyebrow">TARGET CONTACTS</span><h2>HR decision makers</h2></div><span className="job-count">{people.length}/10</span></div><p className="profile-help">Select the people you want to contact. Email addresses are looked up only for the people you select.</p>
 {people.length?<div className="decision-maker-list">{people.map(p=><article className="decision-person" key={p.id}><label className="person-check"><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/><span><strong>{p.name}</strong><span>{p.title||"HR contact"}</span>{p.email&&<span className="contact-email">{p.email}</span>}</span></label>{p.linkedin_url&&<a className="text-link" href={p.linkedin_url} target="_blank" rel="noreferrer">LinkedIn</a>}<button className="primary-button compact" disabled={!p.email||!selected.includes(p.id)||busy} onClick={()=>generatePersonal(p)}>Generate Email</button></article>)}</div>:<div className="empty-state">No HR decision makers were found for this company.</div>}
 <div className="contact-actions"><button className="primary-button" disabled={!selected.length||emailLoading||busy} onClick={getEmails}>{emailLoading?"Finding emails…":"Get Email Addresses"}</button><span>{selected.length} selected · {selectedWithEmail.length} with email</span></div><div className="common-actions"><button className="secondary-button full-button" disabled={!selectedWithEmail.length||busy} onClick={generateCommon}>Generate Common Email</button></div></section>
 {modal&&<div className="modal-backdrop" onClick={()=>!busy&&setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}>{modal==="jd"&&<><span className="eyebrow">JOB DESCRIPTION</span><h2>{job.title}</h2><p>{job.company}</p><div className="jd-popup">{job.description||"No job description was supplied by the source."}</div><button className="secondary-button" onClick={()=>setModal(null)}>Close</button></>}{modal==="personal"&&active&&<><span className="eyebrow">PERSONALIZED EMAIL</span><h2>{active.name}</h2>{!drafts[active.id]?<p>Preparing a personalized email…</p>:<><p>To: {active.email}</p><label>Subject<input value={drafts[active.id].subject} onChange={e=>setDrafts(x=>({...x,[active.id]:{...x[active.id],subject:e.target.value}}))}/></label><label>Message<textarea className="message-box" value={drafts[active.id].body} onChange={e=>setDrafts(x=>({...x,[active.id]:{...x[active.id],body:e.target.value}}))}/></label><div className="modal-actions"><button className="secondary-button" onClick={()=>setModal(null)}>Close</button><button className="primary-button" disabled={busy||!active.email} onClick={()=>send([active.email!],drafts[active.id])}>Review & Send</button></div></>}</>}{modal==="common"&&<><span className="eyebrow">COMMON EMAIL · BCC</span><h2>Reach selected contacts</h2>{!common?<p>Preparing one email for {selectedWithEmail.length} contacts…</p>:<><p>All selected email addresses will be placed in BCC.</p><label>Subject<input value={common.subject} onChange={e=>setCommon({...common,subject:e.target.value})}/></label><label>Message<textarea className="message-box" value={common.body} onChange={e=>setCommon({...common,body:e.target.value})}/></label><div className="modal-actions"><button className="secondary-button" onClick={()=>setModal(null)}>Close</button><button className="primary-button" disabled={busy} onClick={()=>send(selectedWithEmail.map(p=>p.email!),common)}>Review & Send to All</button></div></>}</>}</div></div>}</main>;
}
